# Generated by Django 5.2.3 on 2025-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('data_di_nascita', models.DateField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('timestamp', models.DateField(null=True)),
                ('torneo', models.CharField(max_length=100, null=True)),
                ('squadra', models.CharField(max_length=100, null=True)),
                ('codice_fiscale', models.CharField(max_length=16, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pagato', models.BooleanField(default=False)),
            ],
        ),
    ]
