# Generated by Django 5.2.3 on 2025-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_iscrizioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'verbose_name': 'Iscrizione', 'verbose_name_plural': 'Iscrizioni'},
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='comune_residenza',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='data_rilascio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='ente_rilasciatore',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='indirizzo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='luogo_di_nascita',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='numero_documento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
