# Generated by Django 5.2.3 on 2025-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_iscrizioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='codice_fiscale',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='squadra',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='torneo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
