# Generated by Django 5.2.3 on 2025-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_iscrizioni', '0003_alter_iscrizione_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
